CREATE SCHEMA LGL;

CREATE  TABLE LGL.DIM_CALENDAR ( 
	DIM_CALENDAR_ID      BIGINT NOT NULL   ,
	YEAR_NUMBER          INT    ,
	QUARTER_NUMBER       INT    ,
	QUARTER_NAME         VARCHAR    ,
	MONTH_NUMBER         INT    ,
	MONTH_NAME           VARCHAR(30)    ,
	DAY_NUMBER           INT    ,
	DAY_NAME             VARCHAR(20)    ,
	WEEK_OF_MONTH        INT    ,
	WEEK_OF_YEAR         INT    ,
	WEEKEND              BOOLEAN    ,
	HOLIDAY              BOOLEAN    ,
	SEASON               VARCHAR(10)    ,
	CONSTRAINT PK_DIM_CALENDAR PRIMARY KEY ( DIM_CALENDAR_ID )
 );

COMMENT ON COLUMN LGL.DIM_CALENDAR.WEEKEND IS '0 is a weekday\n1 is a weekend';

COMMENT ON COLUMN LGL.DIM_CALENDAR.HOLIDAY IS '0 means not a holiday\n1 means there is a holiday';

COMMENT ON COLUMN LGL.DIM_CALENDAR.SEASON IS 'Winter  -->   December 21st \nSpring   --> March 21st \nSummer --> June 21st \nFall   ---> September 21st';

CREATE  TABLE LGL.DIM_LOCATION ( 
	LOCATION_ID          INT NOT NULL   ,
	BOROUGH              VARCHAR(100)    ,
	ZONE_NAME            VARCHAR(100)    ,
	SERVICE_AREA         VARCHAR(100)    ,
	CENTROID_LATITUDE    DOUBLE    ,
	CENTROID_LONGITUDE   DOUBLE    ,
	CONSTRAINT PK_DIM_LOCATION PRIMARY KEY ( LOCATION_ID )
 );

CREATE  TABLE LGL.DIM_PAYMENT_TYPE ( 
	PAYMENT_TYPE_ID      INT NOT NULL   ,
	PAYMENT_TYPE_NAME    VARCHAR(50)    ,
	CONSTRAINT PK_DIM_PAYMENT_TYPE PRIMARY KEY ( PAYMENT_TYPE_ID )
 );

CREATE  TABLE LGL.DIM_RATE_CODE ( 
	RATE_CODE_ID         INT NOT NULL   ,
	RATE_CODE_NAME       VARCHAR(50)    ,
	CONSTRAINT PK_DIM_RATE_CODE PRIMARY KEY ( RATE_CODE_ID )
 );

CREATE  TABLE LGL.DIM_TRIP_TYPE ( 
	TRIP_TYPE_ID         INT NOT NULL   ,
	TRIP_TYPE_NAME       VARCHAR(50)    ,
	CONSTRAINT PK_DIM_TRIP_TYPE PRIMARY KEY ( TRIP_TYPE_ID )
 );

CREATE  TABLE LGL.DIM_VENDOR ( 
	VENDOR_ID            INT NOT NULL   ,
	VENDOR_NAME          VARCHAR(50)    ,
	CONSTRAINT PK_DIM_VENDOR PRIMARY KEY ( VENDOR_ID )
 );

CREATE  TABLE LGL.FACT_TRIP ( 
	FACT_TRIP_ID         BIGINT NOT NULL   ,
	PASSENGER_COUNT      INT    ,
	TRIP_DISTANCE        DECIMAL(5,2)    ,
	FARE_AMOUNT          DECIMAL(10,2)    ,
	EXTRA                DECIMAL(10,2)    ,
	MTA                  DECIMAL(10,2)    ,
	TIP_AMOUNT           DECIMAL(10,2)    ,
	TOLLS_AMOUNT         DECIMAL(10,2)    ,
	IMPROVEMENT_SURCHARGE DECIMAL(10,2)    ,
	TOTAL_AMOUNT         DECIMAL(10,2)    ,
	CONGESTION_SURCHARGE DECIMAL(10,2)    ,
	VENDOR_ID            INT NOT NULL   ,
	RATE_CODE_ID         INT NOT NULL   ,
	PAYMENT_TYPE_ID      INT NOT NULL   ,
	TRIP_TYPE_ID         INT NOT NULL   ,
	PICKUP_LOCATION_ID   INT NOT NULL   ,
	DROPOFF_LOCATION_ID  INT NOT NULL   ,
	PICKUP_DATE_ID       BIGINT NOT NULL   ,
	DROPOFF_DATE_ID      BIGINT NOT NULL   ,
	TRIP_DURATION        DECIMAL(12,2)    ,
	TEMPERATURE          DECIMAL(5,2)    ,
	PRECIPITATION_PROBABILITY DECIMAL(5,2)    ,
	RAIN                 DECIMAL(5,2)    ,
	SHOWERS              DECIMAL(5,2)    ,
	SNOWFALL             DECIMAL(5,2)    ,
	SNOW_DEPTH           DECIMAL(5,2)    ,
	WIND_120M            DECIMAL(5,2)    ,
	WIND_180M            DECIMAL(5,2)    ,
	CONSTRAINT PK_FACT_TRIP PRIMARY KEY ( FACT_TRIP_ID )
 );

COMMENT ON COLUMN LGL.FACT_TRIP.TRIP_DURATION IS 'in minutes';

COMMENT ON COLUMN LGL.FACT_TRIP.TEMPERATURE IS 'Farenheit';

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_VENDOR FOREIGN KEY ( VENDOR_ID ) REFERENCES LGL.DIM_VENDOR( VENDOR_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_RATE_CODE FOREIGN KEY ( RATE_CODE_ID ) REFERENCES LGL.DIM_RATE_CODE( RATE_CODE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_PAYMENT_TYPE FOREIGN KEY ( PAYMENT_TYPE_ID ) REFERENCES LGL.DIM_PAYMENT_TYPE( PAYMENT_TYPE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_TRIP_TYPE FOREIGN KEY ( TRIP_TYPE_ID ) REFERENCES LGL.DIM_TRIP_TYPE( TRIP_TYPE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_LOCATION FOREIGN KEY ( PICKUP_LOCATION_ID ) REFERENCES LGL.DIM_LOCATION( LOCATION_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_LOCATION_0 FOREIGN KEY ( DROPOFF_LOCATION_ID ) REFERENCES LGL.DIM_LOCATION( LOCATION_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_CALENDAR FOREIGN KEY ( PICKUP_DATE_ID ) REFERENCES LGL.DIM_CALENDAR( DIM_CALENDAR_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE LGL.FACT_TRIP ADD CONSTRAINT FK_FACT_TRIP_DIM_CALENDAR_0 FOREIGN KEY ( DROPOFF_DATE_ID ) REFERENCES LGL.DIM_CALENDAR( DIM_CALENDAR_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

