{{ config(materialized='table') }}

WITH LOCATION_CTE 
( 
    SELECT 
    LOCATIONID AS LOCATION_ID,
    ZONE AS ZONE_NAME, 
    BOROUGH, 
    LATITUDE AS CENTROID_LATITUDE,
    LONGITUDE AS CENTROID_LONGITUDE
    FROM  LOCATION_RAW
)



SELECT * FROM LOCATION_CTE;